# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

version = 1
SPDX-PackageName = "UCS@school"
SPDX-PackageSupplier = "Univention GmbH <info@univention.de>"
SPDX-PackageDownloadLocation = "https://www.univention.com/products/ucsschool/"

# ENSURE this is in sync with the reuse annotate pre-commit hook
[[annotations]]
path = [
    "basedpyright-baseline.json",
    "openapi-client-udm-1.0.2.tar.gz",
    "pyrightconfig.json",
    "renovate.json",
    "uv.lock",
    ".python-version",
    "univention-lib-slim/changelog",
    "univention-directory-manager-modules-slim/changelog",
    "doc/dev/requirements/requirements-nonfunctional_reference_envs.ods",
    "kelvin-api/empty_configs/global.json",
    "kelvin-api/empty_configs/user_import.json",
    "kelvin-api/empty_configs/user_import_http-api.json",
    "kelvin-api/empty_configs/user_import_legacy.json",
    "kelvin-api/usr/share/ucs-school-import/configs/kelvin_defaults.json",
    "kelvin-connector/src/kelvin_connector/py.typed",
    "ucsschool-objects/src/ucsschool_objects/core/py.typed",
    "ucsschool-objects/src/ucsschool_objects/py.typed",
    "ucsschool-objects/tests/py.typed",
]
SPDX-FileCopyrightText = "2026 Univention GmbH"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [
    "doc/**.png",
    "doc/**.svg",
]
SPDX-FileCopyrightText = "2026 Univention GmbH"
SPDX-License-Identifier = "LicenseRef-Univention-Proprietary"

[[annotations]]
path = [
    "doc/dev/spelling_wordlist",
    "doc/docs/spelling_wordlist",
]
SPDX-FileCopyrightText = "2021-2026 Univention GmbH"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [
    "kelvin-api/static/swagger-ui-standalone-preset.js",
    "kelvin-api/static/swagger-ui-bundle-5.17.14.js",
    "kelvin-api/static/swagger-ui-5.17.14.css",
]
SPDX-FileCopyrightText = "SmartBear Software Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "kelvin-api/static/redoc.standalone-2.0.0-rc.75.js"
SPDX-FileCopyrightText = "2015-present Redoc contributors"
SPDX-License-Identifier = "MIT"

## BEGIN AUTOMATIC GENERATED COPYRIGHT INFORMATION
# This block is auto-generated by update-reuse-toml.py. Do not edit manually.

[[annotations]]
path = "ucs-school-import/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2016-2026 Univention GmbH"

[[annotations]]
path = "ucs-school-import/usr/share/doc/ucs-school-import-http-api/plantuml/plantuml.jar"
precedence = "override"
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "PlantUML"

[[annotations]]
path = "ucs-school-import/modules/ucsschool/importer/contrib/csv.py"
precedence = "override"
SPDX-License-Identifier = "Python-2.0"
SPDX-FileCopyrightText = "2001-2006 Python Software Foundation; All Rights Reserved"

[[annotations]]
path = "ucs-school-lib/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2012-2021 Univention GmbH"

[[annotations]]
path = "ucs-test-ucsschool-kelvin/**"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
SPDX-FileCopyrightText = "2025 Univention GmbH"

## END AUTOMATIC GENERATED COPYRIGHT INFORMATION
