date: '%Y-%m-%d %H:%M:%S'
cmdline: !!omap
-   NOTSET: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   RESPONSE: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   REQUEST: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   DEBUG: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   INFO: '%(message)s'
-   WARNING: '%(levelname)-5s  %(message)s'
-   ERROR: '%(levelname)-5s  %(message)s'
-   CRITICAL: '%(levelname)-5s  %(message)s'
colors: !!omap
-   NOTSET: white
-   RESPONSE: white
-   REQUEST: white
-   DEBUG: white
-   INFO: reset
-   WARNING: yellow
-   ERROR: red
-   CRITICAL: bold_red
file: !!omap
-   NOTSET: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   RESPONSE: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   REQUEST: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   DEBUG: '%(asctime)s %(levelname)-5s %(module)s.%(funcName)s:%(lineno)d  %(message)s'
-   INFO: '%(asctime)s %(levelname)-5s %(message)s'
-   WARNING: '%(asctime)s %(levelname)-5s %(message)s'
-   ERROR: '%(asctime)s %(levelname)-5s %(message)s'
-   CRITICAL: '%(asctime)s %(levelname)-5s %(message)s'
