# SPDX-FileCopyrightText: 2024-2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from ucsschool.kelvin.constants import URL_API_V1_PREFIX, URL_KELVIN_BASE
from ucsschool.kelvin.main import app


@pytest.mark.asyncio
async def test_get_root():
    client = TestClient(app, base_url="http://test.server")
    response = client.get(URL_KELVIN_BASE)
    assert response.url.path == f"{URL_KELVIN_BASE}/docs"


@pytest.mark.parametrize(
    "endpoint,static_file_attr",
    [
        ("changelog", "STATIC_FILE_CHANGELOG"),
        ("readme", "STATIC_FILE_README"),
    ],
)
def test_doc_static_page_is_served(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    endpoint: str,
    static_file_attr: str,
) -> None:
    """The /changelog and /readme endpoints serve their built static HTML file verbatim.

    The files are generated by build_docs.py at image-build time; here we point the
    endpoint at a stand-in file and assert the response is exactly what is on disk.
    """
    static_file = tmp_path / f"{endpoint}.html"
    _ = static_file.write_text(f"<!DOCTYPE html><title>{endpoint}</title><p>{endpoint} body</p>")
    monkeypatch.setattr(f"ucsschool.kelvin.routers.v1.doc.{static_file_attr}", static_file)

    client = TestClient(app, base_url="http://test.server")
    response = client.get(f"{URL_API_V1_PREFIX}/{endpoint}")

    assert response.status_code == 200
    assert response.headers["content-type"].startswith("text/html")
    assert response.text == static_file.read_text()
