# Copyright 2024 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from ucsschool.kelvin.constants import URL_API_V1_PREFIX, URL_KELVIN_BASE
from ucsschool.kelvin.main import app


@pytest.mark.asyncio
async def test_get_root():
    client = TestClient(app, base_url="http://test.server")
    response = client.get(URL_KELVIN_BASE)
    assert response.url.path == f"{URL_KELVIN_BASE}/docs"


@pytest.mark.parametrize(
    "endpoint,static_file_attr",
    [
        ("changelog", "STATIC_FILE_CHANGELOG"),
        ("readme", "STATIC_FILE_README"),
    ],
)
def test_doc_static_page_is_served(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    endpoint: str,
    static_file_attr: str,
) -> None:
    """The /changelog and /readme endpoints serve their built static HTML file verbatim.

    The files are generated by build_docs.py at image-build time; here we point the
    endpoint at a stand-in file and assert the response is exactly what is on disk.
    """
    static_file = tmp_path / f"{endpoint}.html"
    _ = static_file.write_text(f"<!DOCTYPE html><title>{endpoint}</title><p>{endpoint} body</p>")
    monkeypatch.setattr(f"ucsschool.kelvin.routers.v1.doc.{static_file_attr}", static_file)

    client = TestClient(app, base_url="http://test.server")
    response = client.get(f"{URL_API_V1_PREFIX}/{endpoint}")

    assert response.status_code == 200
    assert response.headers["content-type"].startswith("text/html")
    assert response.text == static_file.read_text()
