template(name="HttpLogMsg" type="string" string="%msg:22:$%\n")

if ($syslogtag startswith "artifacts.software-univention.de/ucsschool/ucsschool-kelvin-rest-api") and ($msg startswith " kelvin_api_http_log ") then {
    /var/log/univention/ucsschool-kelvin-rest-api/http.log;HttpLogMsg
    stop
}
