FROM docker-registry.knut.univention.de/python:3.11-slim

RUN apt-get -qq update \
	&& apt-get install -q --assume-yes --no-install-recommends git curl \
    && pip install pre-commit \
	&& rm -rf /var/lib/apt/lists/*_* /var/cache/apt/archives/*.deb

RUN curl -L -o /usr/bin/opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static \
    && chmod +x /usr/bin/opa

ENV HOME /tmp
CMD pre-commit run --all-files
