"""init tables

Baseline migration (down_revision=None) that creates the full initial
schema: all tables, constraints, and the default role rows. The table DDL
was generated via `alembic revision --autogenerate` against the ORM
metadata; the default-role seed insert and the `pg_trgm`/GIN trigram
indexes below were added by hand, since neither is represented in the ORM
metadata.

The trigram indexes cover the fixed set of columns used for indexed
case-insensitive wildcard search (`ILIKE`): user.name, user.firstname,
user.lastname, user.email, school.name, group.name.

Uses plain `CREATE INDEX` (not `CONCURRENTLY`) deliberately, matching this
migration's raw-DDL style. This briefly locks writes to the affected tables
while the indexes are built. Deployments with very large `user`/`school`/`group`
tables should evaluate switching to `CREATE INDEX CONCURRENTLY` via
`op.get_context().autocommit_block()` before running this in production,
and validate that against the advisory-lock context manager in `alembic/env.py`.

Revision ID: e49791148e25
Revises:
Create Date: 2026-07-15 20:11:45.535687

"""
from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e49791148e25"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_ROLES = [
    "teacher",
    "student",
    "legal_guardian",
    "legal_ward",
    "school_class",
    "workgroup",
    "staff",
    "school",
    "school_admin",
]

_TRGM_INDEXES = [
    ("ix_user_name_trgm", "user", "name"),
    ("ix_user_firstname_trgm", "user", "firstname"),
    ("ix_user_lastname_trgm", "user", "lastname"),
    ("ix_user_email_trgm", "user", "email"),
    ("ix_school_name_trgm", "school", "name"),
    ("ix_group_name_trgm", "group", "name"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "display_name",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_role_public_id"), "role", ["public_id"], unique=True)
    role_table = sa.table(
        "role",
        sa.column("public_id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("display_name", sa.JSON()),
    )
    op.bulk_insert(
        role_table,
        [{"public_id": str(uuid4()), "name": name, "display_name": {}} for name in _DEFAULT_ROLES],
    )
    _ = op.create_table(
        "school",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("record_uid", sa.String(length=255), nullable=False),
        sa.Column("source_uid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "educational_servers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "administrative_servers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("class_share_file_server", sa.String(length=255), nullable=True),
        sa.Column("home_share_file_server", sa.String(length=255), nullable=True),
        sa.Column(
            "udm_properties",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("record_uid", "source_uid", name="uq_school_record_source_uid"),
    )
    op.create_index(op.f("ix_school_public_id"), "school", ["public_id"], unique=True)
    _ = op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("record_uid", sa.String(length=255), nullable=False),
        sa.Column("source_uid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("firstname", sa.String(length=255), nullable=False),
        sa.Column("lastname", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("birthday", sa.DATE(), nullable=True),
        sa.Column("expiration_date", sa.DATE(), nullable=True),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "udm_properties",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("record_uid", "source_uid", name="uq_user_record_source_uid"),
    )
    op.create_index(op.f("ix_user_public_id"), "user", ["public_id"], unique=True)
    _ = op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("record_uid", sa.String(length=255), nullable=False),
        sa.Column("source_uid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("has_share", sa.BOOLEAN(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "udm_properties",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["school.id"], ondelete="NO ACTION"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("record_uid", "source_uid", name="uq_group_record_source_uid"),
    )
    op.create_index(op.f("ix_group_public_id"), "group", ["public_id"], unique=True)
    _ = op.create_table(
        "legal_guardian_association",
        sa.Column("legal_guardian_id", sa.Integer(), nullable=False),
        sa.Column("legal_ward_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["legal_guardian_id"], ["user.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["legal_ward_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("legal_guardian_id", "legal_ward_id"),
    )
    _ = op.create_table(
        "school_dn_public_id_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("dn", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(["public_id"], ["school.public_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_school_dn_public_id_mapping_dn"), "school_dn_public_id_mapping", ["dn"], unique=True
    )
    op.create_index(
        op.f("ix_school_dn_public_id_mapping_public_id"),
        "school_dn_public_id_mapping",
        ["public_id"],
        unique=True,
    )
    _ = op.create_table(
        "school_membership",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("primary_user_constraint", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["school.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("primary_user_constraint"),
        sa.UniqueConstraint("user_id", "school_id"),
    )
    _ = op.create_table(
        "user_dn_public_id_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("dn", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(["public_id"], ["user.public_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_dn_public_id_mapping_dn"), "user_dn_public_id_mapping", ["dn"], unique=True
    )
    op.create_index(
        op.f("ix_user_dn_public_id_mapping_public_id"),
        "user_dn_public_id_mapping",
        ["public_id"],
        unique=True,
    )
    _ = op.create_table(
        "group_dn_public_id_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("dn", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(["public_id"], ["group.public_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_dn_public_id_mapping_dn"), "group_dn_public_id_mapping", ["dn"], unique=True
    )
    op.create_index(
        op.f("ix_group_dn_public_id_mapping_public_id"),
        "group_dn_public_id_mapping",
        ["public_id"],
        unique=True,
    )
    _ = op.create_table(
        "group_group_email_senders_association",
        sa.Column("parent_group_id", sa.Integer(), nullable=False),
        sa.Column("child_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["child_group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_group_id"], ["group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_group_id", "child_group_id"),
    )
    _ = op.create_table(
        "group_member_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("school_membership_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_membership_id"], ["school_membership.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "school_membership_id"),
    )
    _ = op.create_table(
        "group_member_role_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "role_id"),
    )
    _ = op.create_table(
        "group_role_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "role_id"),
    )
    _ = op.create_table(
        "group_user_email_senders_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    _ = op.create_table(
        "school_membership_role_association",
        sa.Column("school_membership_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_membership_id"], ["school_membership.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("school_membership_id", "role_id"),
    )
    # ### end Alembic commands ###
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    for index_name, table, column in _TRGM_INDEXES:
        op.execute(
            sa.text(
                f"CREATE INDEX IF NOT EXISTS {index_name} "
                f'ON "{table}" USING gin ("{column}" gin_trgm_ops)'
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    for index_name, _table, _column in _TRGM_INDEXES:
        op.execute(sa.text(f"DROP INDEX IF EXISTS {index_name}"))
    # Intentionally not dropping the pg_trgm extension: a future dynamic
    # UDM-property-index migration may depend on it, and migrations run
    # linearly, so dropping a shared extension here is unsafe.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("school_membership_role_association")
    op.drop_table("group_user_email_senders_association")
    op.drop_table("group_role_association")
    op.drop_table("group_member_role_association")
    op.drop_table("group_member_association")
    op.drop_table("group_group_email_senders_association")
    op.drop_index(
        op.f("ix_group_dn_public_id_mapping_public_id"), table_name="group_dn_public_id_mapping"
    )
    op.drop_index(op.f("ix_group_dn_public_id_mapping_dn"), table_name="group_dn_public_id_mapping")
    op.drop_table("group_dn_public_id_mapping")
    op.drop_index(op.f("ix_user_dn_public_id_mapping_public_id"), table_name="user_dn_public_id_mapping")
    op.drop_index(op.f("ix_user_dn_public_id_mapping_dn"), table_name="user_dn_public_id_mapping")
    op.drop_table("user_dn_public_id_mapping")
    op.drop_table("school_membership")
    op.drop_index(
        op.f("ix_school_dn_public_id_mapping_public_id"), table_name="school_dn_public_id_mapping"
    )
    op.drop_index(op.f("ix_school_dn_public_id_mapping_dn"), table_name="school_dn_public_id_mapping")
    op.drop_table("school_dn_public_id_mapping")
    op.drop_table("legal_guardian_association")
    op.drop_index(op.f("ix_group_public_id"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_user_public_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_school_public_id"), table_name="school")
    op.drop_table("school")
    op.drop_index(op.f("ix_role_public_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
