"""add mapping tables

Revision ID: e8b27dd51414
Revises: f1c5bf519a40
Create Date: 2026-04-22 09:08:54.262075

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8b27dd51414"
down_revision: Union[str, Sequence[str], None] = "f1c5bf519a40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_dn_public_id_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.Integer(), nullable=False),
        sa.Column("dn", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(["public_id"], ["school.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_school_dn_public_id_mapping_dn"), "school_dn_public_id_mapping", ["dn"], unique=True
    )
    op.create_index(
        op.f("ix_school_dn_public_id_mapping_public_id"),
        "school_dn_public_id_mapping",
        ["public_id"],
        unique=True,
    )
    op.create_table(
        "user_dn_public_id_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.Integer(), nullable=False),
        sa.Column("dn", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(["public_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_dn_public_id_mapping_dn"), "user_dn_public_id_mapping", ["dn"], unique=True
    )
    op.create_index(
        op.f("ix_user_dn_public_id_mapping_public_id"),
        "user_dn_public_id_mapping",
        ["public_id"],
        unique=True,
    )
    op.create_table(
        "group_dn_public_id_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.Integer(), nullable=False),
        sa.Column("dn", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(["public_id"], ["group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_dn_public_id_mapping_dn"), "group_dn_public_id_mapping", ["dn"], unique=True
    )
    op.create_index(
        op.f("ix_group_dn_public_id_mapping_public_id"),
        "group_dn_public_id_mapping",
        ["public_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_group_dn_public_id_mapping_public_id"), table_name="group_dn_public_id_mapping"
    )
    op.drop_index(op.f("ix_group_dn_public_id_mapping_dn"), table_name="group_dn_public_id_mapping")
    op.drop_table("group_dn_public_id_mapping")
    op.drop_index(op.f("ix_user_dn_public_id_mapping_public_id"), table_name="user_dn_public_id_mapping")
    op.drop_index(op.f("ix_user_dn_public_id_mapping_dn"), table_name="user_dn_public_id_mapping")
    op.drop_table("user_dn_public_id_mapping")
    op.drop_index(
        op.f("ix_school_dn_public_id_mapping_public_id"), table_name="school_dn_public_id_mapping"
    )
    op.drop_index(op.f("ix_school_dn_public_id_mapping_dn"), table_name="school_dn_public_id_mapping")
    op.drop_table("school_dn_public_id_mapping")
    # ### end Alembic commands ###
