"""init tables

Revision ID: f1c5bf519a40
Revises:
Create Date: 2026-04-22 15:57:35.379614

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1c5bf519a40"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_role_public_id"), "role", ["public_id"], unique=True)
    op.create_table(
        "school",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("record_uid", sa.String(length=255), nullable=False),
        sa.Column("source_uid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("educational_servers", sa.JSON(), nullable=False),
        sa.Column("administrative_servers", sa.JSON(), nullable=False),
        sa.Column("class_share_file_server", sa.String(length=255), nullable=True),
        sa.Column("home_share_file_server", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("record_uid", "source_uid", name="uq_school_record_source_uid"),
    )
    op.create_index(op.f("ix_school_public_id"), "school", ["public_id"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("record_uid", sa.String(length=255), nullable=False),
        sa.Column("source_uid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("firstname", sa.String(length=255), nullable=False),
        sa.Column("lastname", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("birthday", sa.DATE(), nullable=True),
        sa.Column("expiration_date", sa.DATE(), nullable=True),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("record_uid", "source_uid", name="uq_user_record_source_uid"),
    )
    op.create_index(op.f("ix_user_public_id"), "user", ["public_id"], unique=True)
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("record_uid", sa.String(length=255), nullable=False),
        sa.Column("source_uid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("has_share", sa.BOOLEAN(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["school.id"], ondelete="NO ACTION"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("record_uid", "source_uid", name="uq_group_record_source_uid"),
    )
    op.create_index(op.f("ix_group_public_id"), "group", ["public_id"], unique=True)
    op.create_table(
        "legal_guardian_association",
        sa.Column("legal_guardian_id", sa.Integer(), nullable=False),
        sa.Column("legal_ward_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["legal_guardian_id"], ["user.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["legal_ward_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("legal_guardian_id", "legal_ward_id"),
    )
    op.create_table(
        "school_membership",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("primary_user_constraint", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["school.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("primary_user_constraint"),
        sa.UniqueConstraint("user_id", "school_id"),
    )
    op.create_table(
        "group_group_email_senders_association",
        sa.Column("parent_group_id", sa.Integer(), nullable=False),
        sa.Column("child_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["child_group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_group_id"], ["group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_group_id", "child_group_id"),
    )
    op.create_table(
        "group_member_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("school_membership_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_membership_id"], ["school_membership.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "school_membership_id"),
    )
    op.create_table(
        "group_role_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "role_id"),
    )
    op.create_table(
        "group_type_role_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "role_id"),
    )
    op.create_table(
        "group_user_email_senders_association",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_table(
        "school_membership_role_association",
        sa.Column("school_membership_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_membership_id"], ["school_membership.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("school_membership_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("school_membership_role_association")
    op.drop_table("group_user_email_senders_association")
    op.drop_table("group_type_role_association")
    op.drop_table("group_role_association")
    op.drop_table("group_member_association")
    op.drop_table("group_group_email_senders_association")
    op.drop_table("school_membership")
    op.drop_table("legal_guardian_association")
    op.drop_index(op.f("ix_group_public_id"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_user_public_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_school_public_id"), table_name="school")
    op.drop_table("school")
    op.drop_index(op.f("ix_role_public_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
