#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

MACHINE_USER="$(hostname)\$"
MACHINE_PASSWORD="$(cat /etc/machine.secret)"

echo "Building OpenAPI client library using host ${DOCKER_HOST_NAME}..."
update_openapi_client \
  --generator java \
  --jar /kelvin/openapi-generator/jar/openapi-generator-cli-*.jar \
  --insecure \
  --username "$MACHINE_USER" \
  --password "$MACHINE_PASSWORD" \
  "$DOCKER_HOST_NAME"
echo "Finished building OpenAPI client library."
