#!/bin/sh

# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#

BASE_DIR="/var/lib/ucs-test-ucsschool-kelvin-performance"
VENV_DIR="$BASE_DIR/venv"
UCS_TEST_DIR="/usr/share/ucs-test/94_ucsschool-kelvin-performance"

if ! [ -d "$VENV_DIR" ]; then
  echo "Creating virtual env for locust in '$VENV_DIR'..."
  python3 -m venv "$VENV_DIR"
  "$VENV_DIR/bin/pip" install -U pip wheel
  "$VENV_DIR/bin/pip" install -r "$UCS_TEST_DIR/requirements.txt"
  "$VENV_DIR/bin/pip" install --no-deps "$UCS_TEST_DIR"
  rm -rf "$BASE_DIR/build/"
else
  echo "Using existing virtual env for locust in '$VENV_DIR'."
fi

exit 0
