template(name="LogMsg" type="string" string="%msg%\n")

if ($syslogtag contains "ucsschool-kelvin-rest-api") then {
    action(
        type="omfile"
        file="/var/log/univention/ucsschool-kelvin-rest-api/http.log"
        template="LogMsg"
    )
}
