#!/bin/sh

# SPDX-FileCopyrightText: 2020 - 2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

## joinscript api: bindpwdfile

#
#  Join script that runs on the docker host.
#

VERSION=1

APP_ID="ucsschool-kelvin-rest-api"

. /usr/share/univention-join/joinscripthelper.lib

joinscript_init

$(python3 <<-%EOF
{{ 'appcenter/includes/remove_kelvin_posgresql_db_settings.py' | source }}
%EOF
) || die

joinscript_remove_script_from_status_file "$APP_ID"

exit 0
