#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
#
# Univention UCS@school
"""
UCS@school import tool for legacy csv format.
"""

# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

import asyncio
import sys

from ucsschool.importer.legacy.legacy_user_import_cmdline import LegacyUserImportCommandLine


def main():
    ui = LegacyUserImportCommandLine()
    return asyncio.run(ui.main())


if __name__ == "__main__":
    sys.exit(main())
