#!/bin/sh

# Copyright 2025 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

action=$1

case "$action" in
  install)
    cat > /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf << 'EOF'
module(load="imjournal" StateFile="imjournal.state")

template(name="LogMsg" type="string" string="%msg%\n")
if ($!APP_NAME == "ucsschool-kelvin-rest-api") then {
    action(
        type="omfile"
        file="/var/log/univention/ucsschool-kelvin-rest-api/http.log"
        template="LogMsg"
    )
}
EOF
    systemctl restart rsyslog
    cat > /etc/univention/templates/files/etc/logrotate.d/ucsschool-kelvin-rest-api << 'EOF'
@%@UCRWARNING=# @%@

@!@
import univention.lib.ucrLogrotate

name = "ucsschool-kelvin-rest-api"
settings = univention.lib.ucrLogrotate.getLogrotateConfig(name, configRegistry)
print(f"/var/log/univention/{name}/http.log {{")
for setting in sorted(settings):
    print(f"\t{settings[setting]}")
print("\tpostrotate")
print("\t\t/usr/lib/rsyslog/rsyslog-rotate > /dev/null")
print("\tendscript")
print("}")
@!@
EOF
    cat > /etc/univention/templates/info/ucsschool-kelvin-rest-api.info << 'EOF'
Type: file
File: etc/logrotate.d/ucsschool-kelvin-rest-api
Variables: logrotate/.*
EOF
    ucr update
    ucr commit /etc/logrotate.d/ucsschool-kelvin-rest-api
    cat > /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api << 'EOF'
#!/usr/bin/env sh

. /usr/share/univention-lib/ucr.sh

if is_ucr_true ucsschool/kelvin/update-ca-restart; then
    univention-app restart ucsschool-kelvin-rest-api
fi
EOF
    chmod +x /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api
    ;;
  remove)
    rm /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf
    rm /etc/univention/templates/info/ucsschool-kelvin-rest-api.info
    rm /etc/univention/templates/files/etc/logrotate.d/ucsschool-kelvin-rest-api
    rm /etc/logrotate.d/ucsschool-kelvin-rest-api
    rm /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api
    ucr update
    systemctl restart rsyslog
    ;;
esac
