#!/bin/bash

# Copyright 2025 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

action=$1

. /usr/share/univention-lib/all.sh

install_log_duplication() {
    if [ -f /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf ]; then
        return
    fi
    cat > /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf << 'EOF'
template(name="LogMsg" type="string" string="%msg%\n")

if ($syslogtag contains "ucsschool-kelvin-rest-api") then {
    action(
        type="omfile"
        file="/var/log/univention/ucsschool-kelvin-rest-api/http.log"
        template="LogMsg"
    )
}
EOF
    systemctl restart rsyslog
}

install_log_rotation() {
    if [ -f /etc/univention/templates/files/etc/logrotate.d/ucsschool-kelvin-rest-api ]; then
        return
    fi
    cat > /etc/univention/templates/files/etc/logrotate.d/ucsschool-kelvin-rest-api << 'EOF'
@%@UCRWARNING=# @%@

@!@
import univention.lib.ucrLogrotate

name = "ucsschool-kelvin-rest-api"
settings = univention.lib.ucrLogrotate.getLogrotateConfig(name, configRegistry)
print(f"/var/log/univention/{name}/http.log {{")
for setting in sorted(settings):
    print(f"\t{settings[setting]}")
print("\tpostrotate")
print("\t\t/usr/lib/rsyslog/rsyslog-rotate > /dev/null")
print("\tendscript")
print("}")
@!@
EOF
    cat > /etc/univention/templates/info/ucsschool-kelvin-rest-api.info << 'EOF'
Type: file
File: etc/logrotate.d/ucsschool-kelvin-rest-api
Variables: logrotate/.*
EOF
    ucr update
    ucr commit /etc/logrotate.d/ucsschool-kelvin-rest-api
}

install_update_ca_hook() {
    if [ -f /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api ]; then
        return
    fi
    cat > /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api << 'EOF'
#!/usr/bin/env sh

. /usr/share/univention-lib/ucr.sh

if is_ucr_true ucsschool/kelvin/update-ca-restart; then
    univention-app restart ucsschool-kelvin-rest-api
fi
EOF
    chmod +x /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api
}

adjust_kelvin_posgresql_db_settings() {
    # If only one installation is configured,
    # then setting the URI/username will be written to the settings/data object
    python3 <<-%EOF
import json
import os
import sys
from urllib.parse import urlparse

from univention.config_registry import ConfigRegistry
from univention.udm import UDM
from univention.udm.binary_props import Base64Bzip2BinaryProperty
from univention.udm.exceptions import NoObject
from univention.appcenter.app_cache import Apps


ucr = ConfigRegistry().load()
fqdn = f'{ucr.get("hostname")}.{ucr.get("domainname")}'
ldap_base = ucr.get('ldap/base')
superordinate = f'cn=univention,{ldap_base}'
app_name = 'ucsschool-kelvin-rest-api'
mod = UDM.admin().version(2).get('settings/data')

kelvin_db_uri = None
kelvin_db_username = None
kelvin_db_password_file = None

app = Apps().find("ucsschool-kelvin-rest-api")

for setting in app.get_settings():
    if setting.name == "ucsschool/kelvin/db/uri":
        kelvin_db_uri = setting.get_value(app)
    if setting.name == "ucsschool/kelvin/db/username":
        kelvin_db_username = setting.get_value(app)

try:
    obj = mod.get(f'cn={app_name},cn=data,{superordinate}')
    data = json.loads(obj.props.data.raw)

    if len(data['installations']) == 1:
        data['database-uri'] = kelvin_db_uri or data['database-uri']
        data['database-user'] = kelvin_db_username or data['database-user']
        raw_value = json.dumps(data).encode('ascii')
        obj.props.data = Base64Bzip2BinaryProperty('data', raw_value=raw_value)
        obj.save()

except NoObject:
    pass

%EOF
}

install_kelvin_postgresql_db() {

    # Secret for local postgres database
    chmod 640 "/etc/postgresql-kelvin.secret"
    chgrp "DC Backup Hosts" "/etc/postgresql-kelvin.secret"


    data="$(python3 <<-%EOF
import json
import os
import sys
from urllib.parse import urlparse

from univention.config_registry import ConfigRegistry
from univention.udm import UDM
from univention.udm.binary_props import Base64Bzip2BinaryProperty
from univention.udm.exceptions import NoObject
from univention.appcenter.app_cache import Apps


ucr = ConfigRegistry().load()
fqdn = f'{ucr.get("hostname")}.{ucr.get("domainname")}'
ldap_base = ucr.get('ldap/base')
superordinate = f'cn=univention,{ldap_base}'
app_name = 'ucsschool-kelvin-rest-api'
mod = UDM.admin().version(2).get('settings/data')
with open('/etc/postgresql-kelvin.secret', 'r') as fd:
    default_password = fd.read().strip()



default_url = f'postgresql://{fqdn}:5432/ucsschool-kelvin-rest-api?sslmode=require'
kelvin_db_uri = None
kelvin_db_username = None
kelvin_db_password_file = None

app = Apps().find("ucsschool-kelvin-rest-api")
for setting in app.get_settings():
    if setting.name == "ucsschool/kelvin/db/uri":
        kelvin_db_uri = setting.get_value(app)
    if setting.name == "ucsschool/kelvin/db/username":
        kelvin_db_username = setting.get_value(app)
    if setting.name == "ucsschool/kelvin/db/password":
        kelvin_db_password_file = setting.filename
        if not os.path.exists(kelvin_db_password_file):
            with open(kelvin_db_password_file, "w") as f:
                f.write(default_password)

try:
    obj = mod.get(f'cn={app_name},cn=data,{superordinate}')

    data = json.loads(obj.props.data.raw)

    kelvin_db_uri = data['database-uri'] or kelvin_db_uri
    kelvin_db_username = data['database-user'] or kelvin_db_username
    kelvin_db_password_host = data['database-password-host'] or fqdn
    kelvin_db_password_file = data['database-password-path'] or kelvin_db_password_file
    if fqdn not in data['installations']:
        data['installations'].append(fqdn)

except NoObject:
    kelvin_db_uri = kelvin_db_uri or default_url
    kelvin_db_password_host = fqdn
    kelvin_db_username = kelvin_db_username or app_name
    cfg = urlparse(kelvin_db_uri)
    obj = mod.new(superordinate)
    obj.position = f'cn=data,{superordinate}'
    obj.props.name = app_name
    obj.props.data_type = 'string'
    data = {
        'database-uri': kelvin_db_uri,
        'database-user': kelvin_db_username,
        'database-password-host': kelvin_db_password_host,
        'database-password-path': kelvin_db_password_file,
        'installations': [fqdn]
    }

if kelvin_db_uri is None:
    print(f"ERROR: {kelvin_db_uri=} could not be determined.", file=sys.stderr)
if kelvin_db_username is None:
    print(f"ERROR: {kelvin_db_username=} could not be determined.", file=sys.stderr)
if kelvin_db_password_host is None:
    print(f"ERROR: {kelvin_db_password_host=} could not be determined", file=sys.stderr)
if kelvin_db_password_file is None:
    print(f"ERROR: {kelvin_db_password_file=} could not be determined", file=sys.stderr)

raw_value = json.dumps(data).encode('ascii')
obj.props.data = Base64Bzip2BinaryProperty('data', raw_value=raw_value)
obj.save()

print(kelvin_db_uri)
print(kelvin_db_username)
print(kelvin_db_password_host)
print(kelvin_db_password_file)
%EOF
)" || die
    opts=( $(echo -e "$data" | awk -F'\n'  '{print $1, $2}') );
    kelvin_db_uri="${opts[0]}"
    kelvin_db_username="${opts[1]}"
    db_password_host="${opts[2]}"
    db_password_file="${opts[3]}"

    # Secret for either local or remote database
    chmod 640 "/etc/ucsschool/kelvin/postgresql-kelvin.secret"
    chgrp "DC Backup Hosts" "/etc/ucsschool/kelvin/postgresql-kelvin.secret"

    univention-scp /etc/machine.secret "$(hostname)"\$@"$(dig +short $db_password_host)":"$db_password_file" "$db_password_file"

    univention-app configure ucsschool-kelvin-rest-api \
        --set "ucsschool/kelvin/db/uri=$kelvin_db_uri" \
        "ucsschool/kelvin/db/username=$kelvin_db_username" \
        --run-script=no >/dev/null #dont log infos

}


remove_log_duplication() {
    rm /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf
    systemctl restart rsyslog
}

remove_log_rotation() {
    rm /etc/univention/templates/info/ucsschool-kelvin-rest-api.info
    rm /etc/univention/templates/files/etc/logrotate.d/ucsschool-kelvin-rest-api
    rm /etc/logrotate.d/ucsschool-kelvin-rest-api
    ucr update
}

remove_update_ca_hook() {
    rm /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api
}

case "$action" in
  install | upgrade)
    install_log_duplication
    install_log_rotation
    install_update_ca_hook
    install_kelvin_postgresql_db
    ;;
  remove)
    remove_log_duplication
    remove_log_rotation
    remove_update_ca_hook
    ;;
  settings)
    adjust_kelvin_posgresql_db_settings
    ;;
esac
