#!/bin/sh

# Copyright 2025 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

action=$1

case "$action" in
  install)
    cat > /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf << 'EOF'
template(name="HttpLogMsg" type="string" string="%msg:22:$%\n")

if ($syslogtag startswith "artifacts.software-univention.de/ucsschool/ucsschool-kelvin-rest-api") and ($msg startswith " kelvin_api_http_log ") then {
    /var/log/univention/ucsschool-kelvin-rest-api/http.log;HttpLogMsg
    stop
}
EOF
    systemctl restart rsyslog
    cat > /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api << 'EOF'
#!/usr/bin/env sh

. /usr/share/univention-lib/ucr.sh

if is_ucr_true ucsschool/kelvin/update-ca-restart; then
    univention-app restart ucsschool-kelvin-rest-api
fi
EOF
    chmod +x /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api
    ;;
  remove)
    rm /etc/ca-certificates/update.d/ucsschool-kelvin-rest-api
    rm /etc/rsyslog.d/ucsschool-kelvin-rest-api.conf
    systemctl restart rsyslog
    ;;
esac
