#!/bin/sh

# SPDX-FileCopyrightText: 2020 - 2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

echo "$$" > /tmp/update
sleep 15
if [ "$(cat /tmp/update)" = "$$" ]; then
    MACHINE_USER="$HOSTNAME\$"
    MACHINE_PASSWORD=$(cat /etc/machine.secret)
    UPDATE_LOCKFILE="/tmp/update_openapi_client_lock"
    /usr/bin/flock "$UPDATE_LOCKFILE" \
        update_openapi_client \
        --generator java \
        --jar /kelvin/openapi-generator/jar/openapi-generator-cli-*.jar \
        --username "$MACHINE_USER" \
        --password "$MACHINE_PASSWORD" \
        "$DOCKER_HOST_NAME"
    kill -HUP 1
fi
