#!/bin/sh

# SPDX-FileCopyrightText: 2020 - 2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

# restore ucr values from previous app version
bak_files="/var/lib/univention-appcenter/apps/ucsschool-kelvin-rest-api/data/backup/base*.conf"
for bak_files in $bak_files
do
 filename=$(basename "$bak_files")
 [ ! -f "$bak_files" ] || mv -v "$bak_files" "/etc/univention/$filename"
done
