#!/bin/sh

# SPDX-FileCopyrightText: 2020 - 2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

# store ucr values for next app version
mkdir -p "/var/lib/univention-appcenter/apps/ucsschool-kelvin-rest-api/data/backup"
cp -v /etc/univention/base*.conf /var/lib/univention-appcenter/apps/ucsschool-kelvin-rest-api/data/backup/
