#!/bin/sh

# Copyright 2020-2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

## joinscript api: bindpwdfile

#
#  Join script that runs on the docker host.
#

VERSION=1

APP_ID="ucsschool-kelvin-rest-api"

. /usr/share/univention-join/joinscripthelper.lib

joinscript_init

$(python3 <<-%EOF
import json

from univention.config_registry import ConfigRegistry
from univention.udm import UDM
from univention.udm.binary_props import Base64Bzip2BinaryProperty
from univention.udm.exceptions import NoObject


ucr = ConfigRegistry().load()
fqdn = f'{ucr.get("hostname")}.{ucr.get("domainname")}'
ldap_base = ucr.get('ldap/base')
mod = UDM.admin().version(2).get('settings/data')
app_name = 'ucsschool-kelvin-rest-api'

try:
    obj = mod.get(f'cn={app_name},cn=data,cn=univention,{ldap_base}')

    data = json.loads(obj.props.data.raw)
    data['installations'].remove(fqdn)
    if data['installations']:
        raw_value = json.dumps(data).encode('ascii')
        obj.props.data = Base64Bzip2BinaryProperty('data', raw_value=raw_value)
        obj.save()
    else:
        obj.delete()
except NoObject:
    pass

%EOF
) || die

joinscript_remove_script_from_status_file "$APP_ID"

exit 0
