#!/bin/bash

# SPDX-FileCopyrightText: 2026 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

#DEBHELPER#
. /usr/share/univention-lib/all.sh

univention-config-registry set \
	ucsschool/ldap/district/enable?false \
	ucsschool/ldap/default/container/teachers?lehrer \
	ucsschool/ldap/default/container/teachers-and-staff?"lehrer und mitarbeiter" \
	ucsschool/ldap/default/container/admins?admins \
	ucsschool/ldap/default/container/pupils?schueler \
	ucsschool/ldap/default/container/staff?mitarbeiter \
	ucsschool/ldap/default/container/legal_guardians?"sorgeberechtigte" \
	ucsschool/ldap/default/groupprefix/teachers?"lehrer-" \
	ucsschool/ldap/default/groupprefix/admins?"admins-" \
	ucsschool/ldap/default/groupprefix/pupils?"schueler-" \
	ucsschool/ldap/default/groupprefix/staff?"mitarbeiter-" \
	ucsschool/ldap/default/groupprefix/legal_guardians?"sorgeberechtigte-" \
	ucsschool/ldap/default/dcs?"edukativ" \
	ucsschool/ldap/noneducational/create/objects?"true" \
	ucsschool/update/user/role?yes \
	ucsschool/import/generate/mail/domain?yes \
	ucsschool/import/purge-expired-users/cron='50 4 * * *' \
	|| die

eval "$(univention-config-registry shell)"

# set UCR-Variables only during installation to "yes" and not during update
use_marktplatz="no"
use_dhcpsearchbase="no"
if [ "$1" = "configure" -a -z "$2" ] ; then
	use_marktplatz="yes"
	use_dhcpsearchbase="yes"
	univention-config-registry set ucsschool/import/generate/policy/dhcp/dns/clearou?"true"
fi
if [ "$1" = "configure" ]
then
	letter="$(univention-config-registry get samba/homedirletter)"
	if [ -z "$letter" ]
	then
		letter='I:'
	else
		letter="${letter:0:1}:"
	fi
	univention-config-registry set "ucsschool/import/set/homedrive?$letter"
	univention-config-registry set 'ucsschool/import/set/netlogon/script/path?ucs-school-logon.vbs'

	# create empty configuration files to /var, for users to modify
	for FILE in global user_import user_import_legacy user_import_http-api; do
		if ! [ -e /var/lib/ucs-school-import/configs/${FILE}.json ]; then
			echo '{}' > /var/lib/ucs-school-import/configs/${FILE}.json
		fi
	done
fi

univention-config-registry set \
	"ucsschool/import/generate/policy/dhcp/searchbase?${use_dhcpsearchbase}" \
	"ucsschool/import/generate/share/marktplatz?${use_marktplatz}" \
	"ucsschool/import/generate/share/marktplatz/permissions?0777" \
	"ucsschool/import/generate/share/marktplatz/group?Domain Users"

# Remove old ipaddr pyo file:
#   https://forge.univention.org/bugzilla/show_bug.cgi?id=27130
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl 8.0.47-1; then
	if [ -e /usr/share/ucs-school-import/scripts/ipaddr.pyo ]; then
		rm -f /usr/share/ucs-school-import/scripts/ipaddr.pyo
	fi
fi

call_joinscript 35ucs-school-import.inst

# Bug #27549: no longer required after update to UCS@school 3.1
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl 9.0.5; then
	if [ "$server_role" = "domaincontroller_master" ] ; then
		if [ ! "$update31_ucsschool_ou_fileserver_update" = "no" ] ; then
			echo "Updating file server settings at all UCS@school OU objects..."
			/usr/share/ucs-school-import/scripts/ucs-school-update-ou-fileservers --auto-detect
			echo "Finished updating file server settings at all UCS@school OU objects."
		fi
	fi
fi

# Bug #26137: do not create administrative slaves automatically any longer ==>
#             default change during switch from UCS@school 3.2 to 3.2R2
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl 10.0.8 ; then
	if [ "$ucsschool_ldap_default_dcs" = "edukativ verwaltung" ] ; then
		ucr set ucsschool/ldap/default/dcs="edukativ"
	fi
fi

exit 0
